---
- name: Deploy Podman application
  hosts: all
  become: true
  gather_facts: false
  collections:
    - jwerak.podman

  vars:
    podman_app_env_vars:
      - name: ENVIRONMENT
        value: "{{ environment_name }}"
    podman_app_container_image_tag: "{{ application_version }}"

  roles:
    - jwerak.podman.podman_app
