---
- name: Deploy Podman application
  hosts: "{{ target_hosts | default('all') }}"
  become: true
  gather_facts: false
  collections:
    - jwerak.podman

  vars:
    podman_app_env_vars:
      - name: ENVIRONMENT
        value: "{{ environment_name }}"
    podman_app_container_image_tag: "{{ application_version }}"
    podman_app_service_name: "{{ edge_app_service_name }}"

  roles:
    - jwerak.podman.podman_app
