---
- name: Base configuration for all servers
  hosts: all
  gather_facts: false
  
  tasks:
    - name: Setup admin ssh pub key
      ansible.posix.authorized_key:
        user: ec2-user
        key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHwsZxASir/qUm4FCX+YY152oUGD9noMd42F21TNQk51"
        state: present
