---
- name: Set Application version for Group
  hosts: localhost
  gather_facts: false

  vars:
    environment_name: dev
    application_version: 0.0.1

  tasks:
    - name: Set application version to group
      ansible.controller.group:
        name: "{{ environment_name }}"
        inventory: Workshop Inventory
        variables: 
          environment_name: "{{ environment_name }}"
          application_version: "{{ application_version }}"
