- name: Smoke test apllication deploy
  hosts: "{{ target_hosts | default('all') }}"
  gather_facts: false

  vars:
    application_ports: 
      - 80

  tasks:
    - name: local machine can reach web ports
      wait_for:
        host: "{{ ansible_host }}"
        port: "{{ item }}"
        timeout: 5
        state: started
      delegate_to: localhost
      loop: "{{ application_ports }}"

    - name: print message
      ansible.builtin.debug:
        msg: "Application is listening on {{ ansible_host }}:{{ item }}"
      loop: "{{ application_ports }}"
